apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-demo
  template:
    metadata:
      labels:
        app: flask-demo
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "flask-app"
        vault.hashicorp.com/agent-inject-secret-flask.txt: "secret/data/flask-app"
        vault.hashicorp.com/agent-inject-template-flask.txt: |
          {{- with secret "secret/data/flask-app" -}}
          export DB_PASSWORD="{{ .Data.data.DB_PASSWORD }}"
          export ENV="{{ .Data.data.ENV }}"
          {{- end }}
    spec:
      serviceAccountName: flask-app  # ‚Üê critical!
      containers:
      - name: flask
        image: panditaditya1798/argo-k8s:v1
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: vault-secrets
          mountPath: /vault/secrets
          readOnly: true
      volumes:
      - name: vault-secrets
        emptyDir:
          medium: Memory  # secrets never hit disk
